steps:
  - id: Build-docker
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/$PROJECT_ID/production/benek8s:$SHORT_SHA",
        "./app/.",
      ]
    timeout: 900s

  - id: Push-docker
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/$PROJECT_ID/production/benek8s:$SHORT_SHA"]
    timeout: 900s

  - id: envSubst-for-deployment.yml
    name: "gcr.io/$PROJECT_ID/envsubst"
    env:
      - "SHORT_SHA=$SHORT_SHA"
      - "PROJECT_ID=$PROJECT_ID"
    args: ["deployment.yaml"]

  - id: Deploy-to-GKE
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --cluster=bene-cluster
      - --location=asia-southeast1-b
    timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY

# Global Timeout
timeout: "3600s"
