steps:
  - id: Build-docker
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/$PROJECT_ID/production/benek8s:$SHORT_SHA",
        "./app/.",
      ]
    timeout: 900s

  - id: Push-docker
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/$PROJECT_ID/production/benek8s:$SHORT_SHA"]
    timeout: 900s

  - id: envSubst-for-deployment.yml
    name: "gcr.io/$PROJECT_ID/envsubst"
    env:
      - "SHORT_SHA=$SHORT_SHA"
      - "PROJECT_ID=$PROJECT_ID"
    args: ["deployment.yaml"]

  - id: Deploy-to-GKE
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "deployment.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=bene-cluster"
    timeout: 600s

  - id: Verify-deployment
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "rollout"
      - "status"
      - "deployment/bene-cluster"
      - "-n"
      - "production"
      - "--timeout=600s"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=bene-cluster"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "3600s"
